### ISSUE TITLE
Молодец.

### ISSUE THREAD

**Issue by Reactor13** [MrCreepTon/pBot-API#1]
Из-за тебя лег сервер и теперь его пришлось отключить.
Жди повестку в суд за нанесенный материальный ущерб.

**Comment by Reactor13** [comment]
В досудебном порядке предлагаю удалить этот репозиторий и возместить нанесенный ущерб.

**Comment by MrCreepTon** [comment]
Уважаемый. Если вы не можете сменить сигнатуру, а js код обфусцировать, то это сугубо ваши проблемы 🙃

**Comment by Reactor13** [comment]
Т.е. вы отказываетесь удалить этот репозиторий?
Напоминаю, что вы нарушили закон об авторском праве и своими действиями нанесли ущерб нашей компании.

Хорошо, это все будет передано в суд.
